#!/bin/ksh

source ${.sh.file%/*}/../lib/testenv.ksh

start_environment -clean

# List with no zones
name="list no zones"
zadm list >/dev/null && result "$name" PASS || result "$name" FAIL
zadm list | egrep -s '^NAME' && result "$name 2" PASS || result "$name 2" FAIL
[ `zadm list | wc -l` -eq 2 ] && result "$name 3" PASS || result "$name 3" FAIL

# Create two zones
create_zone fred sparse
create_zone barney pkgsrc

name="list two zones"
zadm list >/dev/null && result "$name" PASS || result "$name" FAIL
zadm list | egrep -s '^NAME' && result "$name 2" PASS || result "$name 2" FAIL
[ `zadm list | wc -l` -eq 4 ] && result "$name 3" PASS || result "$name 3" FAIL

stop_environment

